### ISSUE TITLE
DOCs?

### ISSUE THREAD

**Issue by BransonGitomeh** [kjhangiani/ember-cli-jquery-datatables#1]
thanks for this addon, are you planning to add any user docs?...atleast an ember :install command

**Comment by kjhangiani** [comment]
@BransonGitomeh I actually have been working on this considerably, but its currently in our app repo.  I am planning to port the work there over into an abstracted and reusable component here, but I am not sure when.  The version released here is very basic and essentially just includes the library... but I've done some work in "emberifying" it that I plan to move to this repo.

I hope to get to it soon but have a lot on my plate at the moment.. wish I could give you a definite timeline... happy to try and help you out with it if you have specific questions though

**Comment by zynick** [comment]
do you have any sample on how to use it? I cloned your repo, run `ember server`, visit `http://localhost:4200` and got "Welcome to Ember.js"

also based on your component code (https://github.com/kjhangiani/ember-cli-jquery-datatables/blob/master/app/components/jquery-datatable.js, assuming that's how we use it), what can we do after importing jqueryDatable?

thank you for emberify this tool!

**Comment by kjhangiani** [comment]
The component provided is actually just a really simple example, but there's no need to extend or use it.  On any component that contains a table, just add:

```
didInsertElement: function() {
   this.$('table.your-table-class').dataTable({
    //your datatable options
   });
},
```

The addon doesn't do much but give you easy access to the datatables library, how you use it in your app is up to you! :)
