### ISSUE TITLE
Plugins Missing

### ISSUE THREAD

**Issue by jrock2004** [kjhangiani/ember-cli-jquery-datatables#3]
Do I have to manually install the datatables plugins (buttons, responsive, etc..) or is this plugin suppose to install those as well? Thanks

**Comment by kjhangiani** [comment]
Sorry, haven't updated this in a long while - if you use the latest master, you can selectively choose which extensions and style you want to include.  I haven't yet published this to npm, so you'll need to add it to package.json via the github url.

There is one current bug in that the image files don't get included, so you'll need to bower import them yourself in your app's Brocfile

**Comment by kjhangiani** [comment]
Just published the latest to npm, and updated the readme with the new config options.  You should be able to include any combination of js and css now.  The only exception is still the 5-6 image files from the core css which need to be manually imported.
