### ISSUE TITLE
New 0.4.0 Cannot instantiate data tables

### ISSUE THREAD

**Issue by jrock2004** [kjhangiani/ember-cli-jquery-datatables#4]
In previous versions I could do 

```
import Ember from 'ember';

export default Ember.Component.extend({
  didInsertElement() {
    $('.table-services').DataTable({
      "bInfo" : false,
      "bLengthChange": false,
      "bPaginate": false,
      "bScrollInfinite": true,
      "bScrollCollapse": true,
      "sScrollY": "400px"
    });
  },
  actions: {
    closeSidebar() {
      $('.overlay-container').addClass('hidden');
    }
  }
});
```

But now getting error that dataTable is not a function. Did you change the way to instantiate it?

**Comment by kjhangiani** [comment]
I have not changed the way it's instantiated, but the dependencies for jquery-datatables have been updated to (slightly) newer versions.

Your instantiation code looks like it's using a legacy format, as the current datatable options do not use things like `bInfo` or `sScrollY`, they would be `scrollY` and `info`. See the datatables.net site here for information on the correct options to use: https://datatables.net/reference/option/

The DataTables library (of which I have no affiliation with) also has some odd syntax for instantiation vs referencing with respect to the constructor (`.dataTable()` vs `.DataTable()`) so it could be that as well.

For reference, here is the way I currently instantiate the datatable in my app:

```
var dtOptions = {
    pageLength: 50,
    columns: cols,
    order: [[sortIndex, sortDirection]],
    orderCellsTop: true,
    dom: 'rt',
    data: this.get('cleanRecords'),
    deferRender: true,
    lengthMenu: false,
    pagingType: "simple",
    fixedHeader: true,
    scrollY: tableHeight,
    scrollX: true,
    scrollCollapse: true,
    rowId: 'DT_RowId',
};

if (this.get('selectable')) {
    dtOptions.select = {
        style: 'os',
        item: 'rows',
        info: false,
        className: 'dt-selected dt-row-selected',
    };
}

var table = this.$('.jqtable').dataTable(dtOptions);
var tableApi = table.DataTable();

this.set('jqtableApi', tableApi);
```

For convenience (and testing), you can also add the following line so you can reference the datatable api easily from console:

```
window.tableApi = tableApi;
```

**Comment by kjhangiani** [comment]
@jrock2004 did that work for you? going to close this issue
